### ISSUE TITLE
Heartbeat service throws exception.

### ISSUE THREAD

**Issue by yuanhoujun** [air-controller/air-controller-desktop#10]
[+73334 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: Stream has already been
listened to.
[        ] #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
[        ] #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
[        ] #2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
[        ] #3      _Socket.listen (dart:io-patch/socket_patch.dart:2174:31)
[        ] #4      _AsBroadcastStream.listen (dart:async/stream_impl.dart:824:31)
[        ] #5      HeartbeatClientImpl.connectToServer
(package:air_controller/network/heartbeat_client.dart:100:56)
[        ] <asynchronous suspension>
[        ] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: StreamSink is bound to a
stream
[        ] #0      _StreamSinkImpl._controller (dart:io/io_sink.dart:216:7)
[        ] #1      _StreamSinkImpl.add (dart:io/io_sink.dart:136:5)
[        ] #2      _IOSinkImpl.write (dart:io/io_sink.dart:269:5)
[        ] #3      _Socket.write (dart:io-patch/socket_patch.dart:2184:36)
[        ] #4      HeartbeatClientImpl._sendToServer
(package:air_controller/network/heartbeat_client.dart:224:14)
[        ] #5      HeartbeatClientImpl.connectToServer
(package:air_controller/network/heartbeat_client.dart:92:5)
[        ] <asynchronous suspension>

**Comment by yuanhoujun** [comment]
Fixed: [dbff40f6db71048cc565459987bbd08a9528f067](https://github.com/air-controller/air-controller-desktop/commit/dbff40f6db71048cc565459987bbd08a9528f067)
