### ISSUE TITLE
请问苹果电脑不能批量下载手机里的图片吗？

### ISSUE THREAD

**Issue by phh95** [air-controller/air-controller-desktop#24]
DioError [DioErrorType.responsel: Http status error [500] Source stack:

DioMixin.fetch (package:dio/src/dio_mixin.dart:488)

＃1 DioMixin.request (package:dio/src/dio_mixin.dart:483)

#2 DioMixin.get (package:dio/src/dio_ mixin.dart:61)

＃3 Flowder.initDownload (package:flowder/src/flowder.dart:47)

<asynchronous suspension>

#4 Flowder.download (package:flowder/src/flowder.dart:29)

<asvnchronous suspension>

#5 AirControllerClient.copylmagesTo (package:air_controller/repository/aircontroller_client.dart:1518)

<asynchronous suspension>

＃6 imageRepository.copylmagesTo (package:air_controller/repositoryfimage_repository. dart:74)

casynchronous suspension>

---

我在 Intel 芯片、macOS 13 系统的电脑上使用这个软件，多选图片下载，提示上面的错误信息，我问了一下 GPT-4，它给了我下面的回复：

这个错误是由于 HTTP 500 状态码引起的，这是一个服务器端错误。这意味着你的程序试图从服务器获取数据，但服务器遇到了错误并不能完成请求。

错误堆栈显示，问题出现在 Flowder.initDownload 和 Flowder.download 这两个方法中。Flowder 是一个 Dart 包，用于处理文件下载。看起来你的程序在试图下载一些文件时遇到了问题。

这个问题可能有以下几个原因：

你试图访问的服务器可能遇到了问题。这可能是由于服务器内部错误，或者服务器正在进行维护。

你的请求可能有问题。例如，你可能在请求中提供了错误的参数，或者你没有提供必要的参数。

你可能没有正确地处理服务器的响应。例如，服务器可能返回了一个错误的 HTTP 状态码，但你的程序没有正确地处理这个错误。

解决这个问题的方法可能包括：

检查你的服务器是否正常运行。你可以尝试直接访问服务器，或者联系服务器的管理员。

检查你的请求是否正确。你可以检查你的请求参数，或者查看服务器的文档，看看你是否遗漏了什么。

检查你的错误处理代码。你需要确保你的程序能够正确地处理服务器返回的错误。

如果你无法确定问题的原因，你可能需要联系 Flowder 包的维护者，或者寻求其他开发者的帮助。

---
请问是哪里出问题了呢？
感谢您开发的这个软件～

**Comment by yuanhoujun** [comment]
非常抱歉，这应该是一个bug 谢谢反馈
